### ISSUE TITLE
viz/smpl_body_visualizer.py

### ISSUE THREAD

**Issue by daoboke** [facebookresearch/fairmotion#78]
python fairmotion/viz/smpl_body_visualizer.py --input_file tests/data/backflip_a.bvh --body_model_file body_models/smplh/neutral/model.npz --video_output_file output.mp4
OpenCV: FFMPEG: tag 0x44495658/'XVID' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
  0%|                                                    | 0/65 [00:00<?, ?it/s](48,)
  0%|                                                    | 0/65 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "fairmotion/viz/smpl_body_visualizer.py", line 150, in <module>
    main(args)
  File "fairmotion/viz/smpl_body_visualizer.py", line 117, in main
    body_model_pose_data[pose_idx * 3 : pose_idx * 3 + 3] = axis_angles
ValueError: could not broadcast input array from shape (3,) into shape (0,)

**Comment by dpacgopinath** [comment]
HI @daoboke , could you attach the input file `tests/data/backflip_a.bvh`? The script seems to work on other test motion files for me (from the AMASS and AIST datasets).
